---
- name: Exclude packages from EPEL repo
  become: yes
  community.general.ini_file:
    path: /etc/yum.repos.d/epel.repo
    section: epel
    option: excludepkgs
    value: zabbix*
    state: present
    exclusive: yes
    create: no
  notify:
    - dnf_clean_metadata

- name: Install Zabbix RPM repositories
  become: yes
  ansible.builtin.dnf:
    name: "https://repo.zabbix.com/zabbix/{{ zabbix_release }}/release/rhel/{{ ansible_distribution_major_version }}/noarch/zabbix-release-latest-{{ zabbix_release }}.el{{ ansible_distribution_major_version }}.noarch.rpm" # noqa:yaml[line-length]
    state: present
    disable_gpg_check: yes
  notify:
    - dnf_clean_metadata

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Install Zabbix agent
  become: yes
  ansible.builtin.dnf:
    name: zabbix-agent{{ agent_variant }}
    state: present
  notify:
    - restart_zabbix_agent
    - set_zabbix_at_boot
