---
- name: Install the Zabbix repository
  become: yes
  ansible.builtin.apt:
    deb: https://repo.zabbix.com/zabbix/{{ zabbix_release }}/release/debian/pool/main/z/zabbix-release/zabbix-release_latest_{{ zabbix_release }}+debian{{ ansible_distribution_major_version }}_all.deb # noqa:yaml[line-length]

- name: Install the Zabbix agent
  become: yes
  ansible.builtin.apt:
    name: zabbix-agent2
    state: present
    update_cache: yes
  notify:
    - restart_zabbix_agent
    - set_zabbix_at_boot
