---
- name: Configure secondary DNS server Mantis-DNS-02
  hosts: mantis-dns-02
  gather_facts: true

  handlers:
    - name: Import handlers
      ansible.builtin.import_tasks:
        file: "{{ playbook_dir }}/handlers/main.ansible.yml"

  vars:
    shared_modules_dir: "{{ playbook_dir }}/../../by-module"

  tasks:
    # - name: Prerequisites
    #   block:
    #     - name: Install packages
    #       become: true
    #       ansible.builtin.apt:
    #         name:
    #           - syncthing
    #         update_cache: true
    #         state: present

    - name: Configure DNS servers
      ansible.builtin.import_tasks:
        file: "{{ module_dir }}/configure_dns_servers.ansible.yml"
      vars:
        module_dir: "{{ shared_modules_dir }}/network/configure_dns_servers"

    - name: Configure MOTD generator
      ansible.builtin.import_tasks:
        file: "{{ module_dir }}/configure_motd_generator.ansible.yml"
      vars:
        module_dir: "{{ shared_modules_dir }}/system/configure_motd_generator"
