---
- name: Install or update Traefik
  hosts: proxy_servers

  handlers:
      - name: Import handlers
        ansible.builtin.import_tasks:
            file: "{{ playbook_dir }}/handlers/main.ansible.yml"

  tasks:
      - name: Include vars
        ansible.builtin.include_vars:
            file: "{{ playbook_dir }}/vars/main.ansible.yml"

      - name: Get latest and current versions of traefik
        ansible.builtin.import_tasks:
            file: "{{ playbook_dir }}/tasks/get_traefik_version.ansible.yml"

      - name: Install or update traefik
        ansible.builtin.import_tasks:
            file: "{{ playbook_dir }}/tasks/install_or_update.ansible.yml"
        vars:
            traefik_bin_path: /usr/sbin/traefik

      - name: Open firewall ports for http and https entrypoints
        ansible.builtin.include_tasks:
            file: "{{ playbook_dir }}/tasks/open_firewall_ports.ansible.yml"
        vars:
            services: >
                {{
                  [
                    { 'service_name': 'traefik-http', 'service_port': 80, 'service_protocol': 'tcp' },
                    { 'service_name': 'traefik-https', 'service_port': 443, 'service_protocol': 'tcp' }
                  ]
                  + ([
                    { 'service_name': 'traefik-ssh', 'service_port': 222, 'service_protocol': 'tcp' }
                  ] if inventory_hostname in groups['external_proxies'] else [])
                }}
