---
- name: Base playbook to configure the Vanguard k3s cluster nodes
  hosts: vanguard_cluster # Harbinger-KN-01, Hoplite-KN-02, Warden-KN-03
  gather_facts: true

  handlers:
    - name: Import handlers
      ansible.builtin.import_tasks:
        file: "{{ playbook_dir }}/handlers/main.ansible.yml"

  tasks:
    - name: Prerequisites
      block:
        - name: Run OS-specific role
          ansible.builtin.include_role:
            name: rhel

    - name: Configure the iscsi daemon
      become: true
      block:
        - name: Install iscsi-initiator-utils package
          ansible.builtin.dnf:
            name: iscsi-initiator-utils
            state: present

        - name: Ensure the initiator name is set
          ansible.builtin.lineinfile:
            path: /etc/iscsi/initiatorname.iscsi
            regexp: "^InitiatorName="
            line: "InitiatorName=$(/sbin/iscsi-iname)"
            create: true
            mode: "0600"

        - name: Load the iscsi kernel module
          community.general.modprobe:
            name: iscsi_tcp
            state: present

        - name: Ensure the iscsi daemon is enabled and running
          ansible.builtin.systemd:
            name: iscsid.service
            enabled: true
            state: started
