---
- name: Install Nix
  ansible.builtin.import_tasks:
    file: "{{ role_path }}/tasks/install-nix.ansible.yml"

- name: Get Nix profiles
  ansible.builtin.shell: |
    . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
    nix profile list --json
  changed_when: false
  register: current_nix_profiles

- name: Copy Nix profile to root
  become: true
  ansible.builtin.copy:
    src: "{{ role_path }}/files/nix/"
    dest: "/etc/nixconfig"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  register: copy_nix_profile

- name: Define Nix profiles
  ansible.builtin.set_fact:
    nix_profiles: "{{ default_nix_profiles + extra_nix_profiles }}"

- name: Install Nix profiles
  ansible.builtin.shell: |
    . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
    nix profile install /etc/nixconfig#{{ item }}
  when: current_nix_profiles is defined and not current_nix_profiles.stdout | from_json | json_query('elements.' + item + '.active')
  changed_when: true
  with_items: "{{ nix_profiles }}"

- name: Update Nix profile
  ansible.builtin.shell: |
    . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
    nix profile upgrade {{ item }}
  when: current_nix_profiles is defined and current_nix_profiles.stdout | from_json | json_query('elements.' + item + '.active') and copy_nix_profile.changed
  changed_when: true
  with_items: "{{ nix_profiles }}"
