---
- name: Install Nix
  ansible.builtin.import_tasks:
    file: "{{ module_dir }}/tasks/install-nix.ansible.yml"

- name: Get Nix profiles
  ansible.builtin.shell: |
    . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
    nix profile list --json
  changed_when: false
  register: nix_profiles

- name: Copy Nix profile to root
  ansible.builtin.copy:
    src: "{{ module_dir }}/nix/"
    dest: "/etc/nixconfig"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  register: copy_nix_profile

- name: Install Nix profile
  ansible.builtin.shell: |
    . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
    nix profile install /etc/nixconfig
  when: nix_profiles is defined and not nix_profiles.stdout | from_json | json_query('elements.nixconfig.active')
  changed_when: true

- name: Update Nix profile
  ansible.builtin.shell: |
    . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
    nix profile upgrade nixconfig
  when: nix_profiles is defined and nix_profiles.stdout | from_json | json_query('elements.nixconfig.active') and copy_nix_profile.changed
  changed_when: true
