---
- name: Install the UFW package
  become: yes
  ansible.builtin.package:
    name: ufw
    state: present

- name: Allow SSH connections
  become: yes
  community.general.ufw:
    rule: allow
    port: 22
    proto: tcp

- name: Enable UFW
  become: yes
  community.general.ufw:
    state: enabled
