---
# tasks file for configure_rhel_servers
- name: Configure subscription and Red Hat Connect
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/setup_redhat_connect.ansible.yml"

- name: Add user to docker group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  when: "'docker_servers' in group_names"

- name: Enable Pressure Stall Information (PSI)
  become: true
  ansible.builtin.command:
    cmd: "grubby --update-kernel=ALL --args='psi=1'"
  when: ansible_distribution_major_version == "9" and ansible_kernel >= "4.20.0"
  changed_when: ansible_cmdline.psi is not defined or ansible_cmdline.psi != "1"
  notify: reboot-needed
