---
# tasks file for rhel
- name: Configure default user
  when: semaphore_vars is not defined
  block:
    - name: Get cloud-user infos
      ansible.builtin.getent:
        database: passwd
        key: cloud-user
      register: cloud_user_info
      changed_when: false
      failed_when: false

    - name: Set remote user
      ansible.builtin.set_fact:
        remote_super_user: "cloud-user"
      when: cloud_user_info.ansible_facts is defined

    - name: Set password for default user
      become: true
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        password: "{{ '%s' | format(ansible_become_password) | regex_replace('\n', '') | password_hash('sha512', 'salt') }}"
      when: ansible_user_id != "root"
      vars:
        ansible_user: "{{ remote_super_user | default('root') }}"

- name: Configure subscription and Red Hat Connect
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/setup_redhat_connect.ansible.yml"

- name: Configure DNS servers
  ansible.builtin.include_role:
    name: dns_servers
  when: not 'linux_containers' in group_names

- name: Configure MOTD generator
  ansible.builtin.include_role:
    name: motd_generator

- name: Add user to docker group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  when: "'docker_servers' in group_names"

- name: Enable Pressure Stall Information (PSI)
  become: true
  ansible.builtin.command:
    cmd: "grubby --update-kernel=ALL --args='psi=1'"
  when: ansible_distribution_major_version == "9" and ansible_kernel >= "4.20.0"
  changed_when: ansible_cmdline.psi is not defined or ansible_cmdline.psi != "1"
  notify: reboot-needed

- name: Disable IPv6
  become: true
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: "1"
    state: present
    reload: true
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6
