---
- name: Activate Red Hat subscription
  become: true
  community.general.redhat_subscription:
    state: present
    activationkey: "{{ redhat_activation_key }}"
    org_id: "{{ redhat_org_id }}"

- name: Configure DNF
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/setup_dnf.ansible.yml"

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Install Red Hat Connect
  become: true
  ansible.builtin.dnf:
    name: rhc
    state: present

- name: Get RHC status
  become: true
  ansible.builtin.command:
    cmd: rhc status
  register: rhc_status
  changed_when: false
  failed_when: false

- name: Enable Red Hat Insights
  become: true
  ansible.builtin.command:
    cmd: insights-client --register
  register: rhc_insights
  when: "'Not connected to Red Hat Insights' in rhc_status.stdout"
  failed_when: "'Successfully registered host' not in rhc_insights.stdout and 'Successfully uploaded report' not in rhc_insights.stdout"
  changed_when: true
