- name: Determine latest GitHub release (local) # noqa: run-once[task]
  delegate_to: localhost
  ansible.builtin.uri:
      url: "https://api.github.com/repos/prometheus/node_exporter/releases/latest"
      body_format: json
  register: _github_release
  until: _github_release.status == 200
  run_once: true
  retries: 5
  when: true

- name: Set node_exporter_version
  ansible.builtin.set_fact:
      node_exporter_version: "{{ _github_release.json.tag_name
          | regex_replace('^v?([0-9\\.]+)$', '\\1') }}"
  when: _github_release.status == 200
